# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-e717036a-ef6f-4bb8-b0c8-861d1ea9be3b";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-e717036a-ef6f-4bb8-b0c8-861d1ea9be3b".device = "/dev/disk/by-uuid/e717036a-ef6f-4bb8-b0c8-861d1ea9be3b";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/0F75-F696";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-b3f288d2-2f13-4485-a92f-9873a8db58fa"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}

