# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-0166b680-0c1f-4559-87fa-3cd2a86a0f9c";
      fsType = "btrfs";
    };

  boot.initrd.luks.devices."luks-0166b680-0c1f-4559-87fa-3cd2a86a0f9c".device = "/dev/disk/by-uuid/0166b680-0c1f-4559-87fa-3cd2a86a0f9c";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-0166b680-0c1f-4559-87fa-3cd2a86a0f9c";
      fsType = "btrfs";
      options = [ "subvol=home" ];
    };

  fileSystems."/nix" =
    { device = "/dev/mapper/luks-0166b680-0c1f-4559-87fa-3cd2a86a0f9c";
      fsType = "btrfs";
      options = [ "subvol=nix" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A731-7E65";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-d5a7c6ca-51d8-45bb-b673-3831da4c9c7c"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
